const products = [
  {
    name: 'Coding Cosmo',
    description: 'a delicious cosmo with a refreshing twist',
    imageUrl:
      'https://media.seedlipdrinks.com/PR1802/media/somdsdzo/cosnopolitan-2.png',
    price: 1000,
    quantity: 10,
  },
  {
    name: 'Binary Booch',
    description: 'a delicious garden mojito',
    imageUrl:
      'https://images.ctfassets.net/b0q5etab7zkl/3nhNtBkB1equESuWm8IeoM/675cf4b86d42c93a761146d3836559e9/Garden_Booch-tinyjpg.jpg?fm=jpg&q=90&w=800&h=1120&fit=fill',
    price: 1000,
    quantity: 10,
  },
  {
    name: 'Python Paloma',
    description: 'a deliciuos spiced paloma',
    imageUrl:
      'https://images.ctfassets.net/b0q5etab7zkl/3lgiCta6EosQZRjLLn5n8F/65c43983a7dc94e6e977b632623b4499/Spice_PaNoma.jpg?fm=jpg&q=90&w=800&h=1120&fit=fill',
    price: 1000,
    quantity: 10,
  },
  {
    name: 'Express-o Martini',
    description: 'a delicious espresso martini',
    imageUrl:
      'https://images.ctfassets.net/b0q5etab7zkl/2lSsuxgBOgwKGuuWsUYYMe/8fd1096ef2a496e2536c69d07577cce3/Espresso_Martino-tinyjpg.jpg?fm=jpg&q=90&w=800&h=1120&fit=fill',
    price: 1000,
    quantity: 10,
  },
  {
    name: 'MEAN Margarita',
    description: 'a delicious classic margarita',
    imageUrl:
      'https://images.ctfassets.net/b0q5etab7zkl/3D3G1QG2Z9Fk6M7bEZCWQl/f0a1959f00229c03854baf5822314d01/Grove_42_Margarita_cocktail_only.jpg?fm=jpg&q=90&w=800&h=1120&fit=fill',
    price: 1000,
    quantity: 10,
  },
  {
    name: 'Pixel Pumpkin',
    description: 'a delicious Ginger + Pumpkin refresher',
    imageUrl:
      'https://images.ctfassets.net/b0q5etab7zkl/5wGt6giEJsJGjFB8TX3JAe/48ddd963d041e5c103151c748e66ca7f/Spice_94_Ginger_Pumpkin_Soda.jpg?fm=jpg&q=90&w=800&h=1120&fit=fill',
    price: 1000,
    quantity: 10,
  },
  {
    name: 'Big O Booch',
    description: 'a delicious Rosemary Booch',
    imageUrl:
      'https://images.ctfassets.net/b0q5etab7zkl/26yrQskXtqm2SeSE2mUIOo/846d8e041800f157bba35505678c5629/Rosemary_Booch.png?fm=jpg&q=90&w=800&h=1120&fit=fill',
    price: 1000,
    quantity: 10,
  },
  {
    name: 'Back End Blossom',
    description: 'a delicious Sour Blossom',
    imageUrl:
      'https://media.seedlipdrinks.com/PR1802/media/i1wmenp3/sour-blossom.jpg?width=475&height=900&mode=crop',
    price: 1000,
    quantity: 10,
  },
  {
    name: 'Token Tonic',
    description: 'A refreshing token with unique flavors',
    imageUrl:
      'https://images.ctfassets.net/b0q5etab7zkl/5C14WUx5TyOWy0mmMSqQys/0a73fa0d423e3d2b870fd14b1d3bb1ce/Grove_Tonic.jpg?fm=jpg&q=90&w=800&h=1120&fit=fill',
    price: 1000,
    quantity: 10,
  },
  {
    name: 'Syntax Sour',
    description: 'a delicious Garden Sour',
    imageUrl:
      'https://media.seedlipdrinks.com/PR1802/media/gd1pyhux/garden-sour.jpg?width=475&height=900&mode=crop',
    price: 1000,
    quantity: 10,
  },
  //   ...new stuff
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
  {
    name: '',
    description: '',
    imageUrl: '',
    price: 1000,
    quantity: 10,
  },
];
